#!/bin/sh

set -e

echo "Configuring lighttpd..."
service lighttpd start

echo "Configuring piaware..."
mkdir -p /run/piaware
chown piaware:piaware /run/piaware
if [ -n "$FA_USER" ]; then
    piaware-config flightaware-user "$FA_USER"
fi
if [ -n "$FA_PASSWORD" ]; then
    piaware-config flightaware-password "$FA_PASSWORD"
fi
if [ -n "$FA_FEEDER_ID" ]; then
    piaware-config feeder-id "$FA_FEEDER_ID"
fi
service piaware start

if [ -n "$FR24KEY" ]; then
    echo "Configuring fr24feed..."
    mkdir -p /var/log/fr24feed /run/fr24feed
    touch /etc/fr24feed.ini
    chmod 0600 /etc/fr24feed.ini
    chown fr24feed:fr24feed /var/log/fr24feed /run/fr24feed /etc/fr24feed.ini
    cat >/etc/fr24feed.ini <<EOM
receiver="avr-tcp"
fr24key="${FR24KEY}"
host="127.0.0.1:30002"
bs="no"
raw="no"
logmode="2"
logpath="/var/log/fr24feed"
mlat="yes"
mlat-without-gps="yes"
EOM
    /sbin/start-stop-daemon --start --oknodo --background --user fr24feed \
        --pidfile /run/fr24feed/fr24feed.pid --make-pidfile \
        --chuid fr24feed --exec /usr/local/bin/fr24feed --
fi

if [ -z "$ENABLE_ADSBEXCHANGE" ]; then
    ENABLE_ADSBEXCHANGE=yes
fi
if [ "$ENABLE_ADSBEXCHANGE" = "yes" ]; then
    echo "Configuring feed-adsbexchange..."
    mkdir -p /run/adsbexchange
    chown adsbexchange:adsbexchange /run/adsbexchange
    /sbin/start-stop-daemon --start --oknodo --background --user adsbexchange \
        --pidfile /run/adsbexchange/feed-adsbexchange.pid --make-pidfile \
        --chuid adsbexchange --exec /usr/local/bin/feed-adsbexchange --
fi

while [ ! -e /var/cache/piaware/feeder_id ]; do
    echo "Waiting for piaware to set feeder_id..."
    sleep 5
done

echo "Configuring dump1090-fa..."
mkdir -p /run/dump1090-fa
chown dump1090-fa:dump1090-fa /run/dump1090-fa
chown -R dump1090-fa:dump1090-fa /dev/bus/usb || true

. /etc/default/dump1090-fa
if [ -e /var/cache/piaware/location.env ]; then
  . /var/cache/piaware/location.env
fi

/sbin/start-stop-daemon --start --oknodo --background --user dump1090-fa \
    --pidfile /run/dump1090-fa/dump1090-fa.pid --make-pidfile \
    --chuid dump1090-fa --exec /usr/bin/dump1090-fa -- \
    $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $JSON_OPTIONS $PIAWARE_DUMP1090_LOCATION_OPTIONS \
    --write-json /run/dump1090-fa --quiet

sleep 5

while true; do
    echo
    date
    if [ -n "${PIAWARE_LAT}${PIAWARE_LON}" ]; then
        echo "Receiver location: ${PIAWARE_LAT} ${PIAWARE_LON}"
    fi
    piaware-status
    sleep 300
done
