#!/bin/sh

set -e

echo "Configuring lighttpd..."
service lighttpd start

echo "Configuring piaware..."
mkdir -p /run/piaware
chown piaware:piaware /run/piaware
if [ -n "$FA_USER" ]; then
    piaware-config flightaware-user "$FA_USER"
fi
if [ -n "$FA_PASSWORD" ]; then
    piaware-config flightaware-password "$FA_PASSWORD"
fi
if [ -n "$FA_FEEDER_ID" ]; then
    piaware-config feeder-id "$FA_FEEDER_ID"
fi
service piaware start

while [ ! -e /var/cache/piaware/feeder_id ]; do
    echo "Waiting for piaware to set feeder_id..."
    sleep 5
done

echo "Configuring dump1090-fa..."
mkdir -p /run/dump1090-fa
chown dump1090-fa:dump1090-fa /run/dump1090-fa
chown -R dump1090-fa:dump1090-fa /dev/bus/usb || true

. /etc/default/dump1090-fa
if [ -e /var/cache/piaware/location.env ]; then
  . /var/cache/piaware/location.env
fi

/sbin/start-stop-daemon --start --oknodo --background --user dump1090-fa \
    --pidfile /run/dump1090-fa/dump1090-fa.pid --make-pidfile \
    --chuid dump1090-fa --exec /usr/bin/dump1090-fa -- \
    $RECEIVER_OPTIONS $DECODER_OPTIONS $NET_OPTIONS $JSON_OPTIONS $PIAWARE_DUMP1090_LOCATION_OPTIONS \
    --write-json /run/dump1090-fa --quiet

sleep 5

while true; do
    echo
    date
    if [ -n "${PIAWARE_LAT}${PIAWARE_LON}" ]; then
        echo "Receiver location: ${PIAWARE_LAT} ${PIAWARE_LON}"
    fi
    piaware-status
    sleep 300
done
